import dayjs from 'dayjs';
import { Vehicle, VehicleType, DriverType} from "../types";

export const vehicleTypes: VehicleType[] = [
  {
    _id: "vtype1",
    name: "Camión Articulado",
    description: "Camión con remolque articulado",
  },
  {
    _id: "vtype2",
    name: "Camión Rígido",
    description: "Camión sin remolque",
  },
  {
    _id: "vtype3",
    name: "Furgón",
    description: "Vehículo cerrado para transporte de mercancías",
  },
  {
    _id: "vtype4",
    name: "Camioneta",
    description: "Vehículo ligero para transporte de mercancías",
  },
  {
    _id: "vtype5",
    name: "Tractor con Semirremolque",
    description: "Combinación de tractor y semirremolque",
  },
]

export const driverTypes: DriverType[] = [
  {
    "_id": "dri1",
    "name": "Carlos",
    "surname": "Gutierrez",
    "dni": 17295772,
    "date_birth": null,
    "company": "5673",
    "vehicle": "9483"
  },
  {
    "_id": "dri2",
    "name": "Esteban",
    "surname": "Rodriguez",
    "dni": 25637829,
    "date_birth": null,
    "company": "4127",
    "vehicle": "3856"
  },
  {
    "_id": "dri3",
    "name": "Marcos",
    "surname": "Bustamante",
    "dni": 37896521,
    "date_birth": null,
    "company": "7895",
    "vehicle": "1274"
  },
  {
    "_id": "dri4",
    "name": "Laura",
    "surname": "Fernandez",
    "dni": 41235678,
    "date_birth": null,
    "company": "2153",
    "vehicle": "9374"
  }
]
export const vehicles: Vehicle[] = [
  {
    _id: "veh1",
    patente: "ABC123",
    modelo: "Toyota",
    marca: "Toyota",
    año: 2020,
    volumen_carga: 1000,
    peso_carga: 1500,
    tipo: "Camión Articulado",
    empresa: "Transportista A",
  },
  {
    _id: "veh2",
    patente: "DEF456",
    modelo: "Ford",
    marca: "Ford",
    año: 2019,
    volumen_carga: 1500,
    peso_carga: 2000,
    tipo: "Camioneta",
    empresa: "Transportista B",
  },
  {
    _id: "veh3",
    patente: "GHI789",
    modelo: "Chevrolet",
    marca: "Chevrolet",
    año: 2021,
    volumen_carga: 1200,
    peso_carga: 1800,
    tipo: "Tractor con Semirremolque",
    empresa: "Transportista C",
  },
  {
    _id: "veh4",
    patente: "JKL012",
    modelo: "Nissan",
    marca: "Nissan",
    año: 2022,
    volumen_carga: 800,
    peso_carga: 1200,
    tipo: "Camión Articulado",
    empresa: "Transportista D",
  },
  {
    _id: "veh5",
    patente: "MNO345",
    modelo: "Hyundai",
    marca: "Hyundai",
    año: 2023,
    volumen_carga: 900,
    peso_carga: 1300,
    tipo: "Camión Rígido",
    empresa: "Transportista E",
  },
  {
    _id: "veh6",
    patente: "PQR678",
    modelo: "Kia",
    marca: "Kia",
    año: 2020,
    volumen_carga: 1100,
    peso_carga: 1600,
    tipo: "Camión Articulado",
    empresa: "Transportista F",
  },
  {
    _id: "veh7",
    patente: "STU901",
    modelo: "Volkswagen",
    marca: "Volkswagen",
    año: 2018,
    volumen_carga: 1300,
    peso_carga: 1700,
    tipo: "Camión Articulado",
    empresa: "Transportista G",
  },
  {
    _id: "veh8",
    patente: "VWX234",
    modelo: "Subaru",
    marca: "Subaru",
    año: 2017,
    volumen_carga: 1400,
    peso_carga: 1900,
    tipo: "Camión Rígido",
    empresa: "Transportista H",
  },
  {
    _id: "veh9",
    patente: "XYZ567",
    modelo: "Mazda",
    marca: "Mazda",
    año: 2021,
    volumen_carga: 950,
    peso_carga: 1400,
    tipo: "Camión Articulado",
    empresa: "Transportista I",
  },
  {
    _id: "veh10",
    patente: "LMN890",
    modelo: "Honda",
    marca: "Honda",
    año: 2022,
    volumen_carga: 1050,
    peso_carga: 1550,
    tipo: "Camión Rígido",
    empresa: "Transportista J",
  }
]
