/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Gestión de Viajes API
 * Documentación de la API para la gestión de viajes
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface CreateTipoVehiculoDto {
  /** Nombre del tipo de vehículo */
  nombre: string;
  /** Descripción del tipo de vehículo */
  descripcion: string;
}

export interface TipoVehiculoDto {
  /** ID del tipo de vehículo */
  _id: string;
  /** Nombre del tipo de vehículo */
  nombre: string;
  /** Descripción del tipo de vehículo */
  descripcion: string;
}

export interface UpdateTipoVehiculoDto { [key: string]: unknown }

export interface CreateVehiculoDto {
  /** Patente del vehículo (formato válido: ABC123 o AB123CD) */
  patente: string;
  /** Marca del vehículo */
  marca: string;
  /** Modelo del vehículo */
  modelo: string;
  /**
   * Año de fabricación (entre 1900 y el año actual)
   * @minimum 1900
   * @maximum 2025
   */
  año: number;
  /**
   * Volumen máximo de carga en m³
   * @minimum 0.01
   */
  volumen_carga: number;
  /**
   * Peso máximo de carga en kilogramos
   * @minimum 0.01
   */
  peso_carga: number;
  /** ID del tipo de vehículo (referencia a tipoVehiculo) */
  tipo: string;
  /** ID de la empresa a la que pertenece el vehículo */
  empresa: string;
}

export interface CreateEmpresaDto {
  /** Razón social de la empresa */
  razon_social: string;
  /** Nombre comercial de la empresa */
  nombre_comercial: string;
  /** CUIT de la empresa (único) */
  cuit: string;
  /** Domicilio fiscal */
  domicilio_fiscal: string;
  /** Teléfono de contacto */
  telefono: string;
  /** Correo electrónico */
  mail: string;
  /** Nombre del contacto de la empresa */
  nombre_contacto: string;
}

export interface VehiculoDto {
  /** ID del vehículo */
  _id: string;
  /** Patente del vehículo (formato válido: ABC123 o AB123CD) */
  patente: string;
  /** Marca del vehículo */
  marca: string;
  /** Modelo del vehículo */
  modelo: string;
  /**
   * Año de fabricación (entre 1900 y el año actual)
   * @minimum 1900
   * @maximum 2025
   */
  año: number;
  /**
   * Volumen máximo de carga en m³
   * @minimum 0.01
   */
  volumen_carga: number;
  /**
   * Peso máximo de carga en kilogramos
   * @minimum 0.01
   */
  peso_carga: number;
  /** ID del tipo de vehículo (referencia a tipoVehiculo) */
  tipo: TipoVehiculoDto;
  /** ID de la empresa a la que pertenece el vehículo */
  empresa: CreateEmpresaDto;
}

export interface UpdateVehiculoDto { [key: string]: unknown }

export interface Empresa { [key: string]: unknown }

export interface UpdateEmpresaDto { [key: string]: unknown }

export interface CreateChoferDto {
  /** Nombre del chofer */
  nombre: string;
  /** Apellido del chofer */
  apellido: string;
  /** DNI del chofer */
  dni: number;
  /** Fecha de nacimiento */
  fecha_nacimiento: string;
  /** Número de licencia del conductor */
  licencia: string;
  /** Tipo de licencia según clasificación nacional */
  tipo_licencia: string;
  /** Número de teléfono del chofer */
  telefono: string;
  /** Correo electrónico del chofer */
  email: string;
  /** ID de la empresa transportista asignada al chofer */
  empresa: string;
  /** ID del vehículo asignado al chofer */
  vehiculo: string;
}

export interface ChoferDto {
  /** ID del chofer */
  _id: string;
  /** Nombre del chofer */
  nombre: string;
  /** Apellido del chofer */
  apellido: string;
  /** DNI del chofer */
  dni: number;
  /** Fecha de nacimiento */
  fecha_nacimiento: string;
  /** Número de licencia del conductor */
  licencia: string;
  /** Tipo de licencia según clasificación nacional */
  tipo_licencia: string;
  /** Número de teléfono del chofer */
  telefono: string;
  /** Correo electrónico del chofer */
  email: string;
  empresa: CreateEmpresaDto;
  vehiculo: CreateVehiculoDto;
}

export interface UpdateChoferDto { [key: string]: unknown }

export const appControllerGetHello = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/`,options
    );
  }


export const getAppControllerGetHelloQueryKey = () => {
    return [`/`] as const;
    }

    
export const getAppControllerGetHelloQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHello>>> = ({ signal }) => appControllerGetHello({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppControllerGetHelloQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
export type AppControllerGetHelloQueryError = AxiosError<unknown>


export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetHelloQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Crear un tipo de vehículo
 */
export const tipoVehiculoControllerCreate = (
    createTipoVehiculoDto: CreateTipoVehiculoDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TipoVehiculoDto>> => {
    
    
    return axios.post(
      `/tipo_vehiculo`,
      createTipoVehiculoDto,options
    );
  }



export const getTipoVehiculoControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerCreate>>, TError,{data: CreateTipoVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerCreate>>, TError,{data: CreateTipoVehiculoDto}, TContext> => {

const mutationKey = ['tipoVehiculoControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tipoVehiculoControllerCreate>>, {data: CreateTipoVehiculoDto}> = (props) => {
          const {data} = props ?? {};

          return  tipoVehiculoControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TipoVehiculoControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tipoVehiculoControllerCreate>>>
    export type TipoVehiculoControllerCreateMutationBody = CreateTipoVehiculoDto
    export type TipoVehiculoControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Crear un tipo de vehículo
 */
export const useTipoVehiculoControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerCreate>>, TError,{data: CreateTipoVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tipoVehiculoControllerCreate>>,
        TError,
        {data: CreateTipoVehiculoDto},
        TContext
      > => {

      const mutationOptions = getTipoVehiculoControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Obtener todos los tipos de vehículo
 */
export const tipoVehiculoControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TipoVehiculoDto[]>> => {
    
    
    return axios.get(
      `/tipo_vehiculo`,options
    );
  }


export const getTipoVehiculoControllerFindAllQueryKey = () => {
    return [`/tipo_vehiculo`] as const;
    }

    
export const getTipoVehiculoControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTipoVehiculoControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>> = ({ signal }) => tipoVehiculoControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TipoVehiculoControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>>
export type TipoVehiculoControllerFindAllQueryError = AxiosError<void>


export function useTipoVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTipoVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTipoVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener todos los tipos de vehículo
 */

export function useTipoVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTipoVehiculoControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Obtener un tipo de vehículo por ID
 */
export const tipoVehiculoControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TipoVehiculoDto>> => {
    
    
    return axios.get(
      `/tipo_vehiculo/${id}`,options
    );
  }


export const getTipoVehiculoControllerFindOneQueryKey = (id: string,) => {
    return [`/tipo_vehiculo/${id}`] as const;
    }

    
export const getTipoVehiculoControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError = AxiosError<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTipoVehiculoControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>> = ({ signal }) => tipoVehiculoControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TipoVehiculoControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>>
export type TipoVehiculoControllerFindOneQueryError = AxiosError<void>


export function useTipoVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTipoVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTipoVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener un tipo de vehículo por ID
 */

export function useTipoVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tipoVehiculoControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTipoVehiculoControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Actualizar un tipo de vehículo
 */
export const tipoVehiculoControllerUpdate = (
    id: string,
    updateTipoVehiculoDto: UpdateTipoVehiculoDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TipoVehiculoDto>> => {
    
    
    return axios.patch(
      `/tipo_vehiculo/${id}`,
      updateTipoVehiculoDto,options
    );
  }



export const getTipoVehiculoControllerUpdateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerUpdate>>, TError,{id: string;data: UpdateTipoVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerUpdate>>, TError,{id: string;data: UpdateTipoVehiculoDto}, TContext> => {

const mutationKey = ['tipoVehiculoControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tipoVehiculoControllerUpdate>>, {id: string;data: UpdateTipoVehiculoDto}> = (props) => {
          const {id,data} = props ?? {};

          return  tipoVehiculoControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TipoVehiculoControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof tipoVehiculoControllerUpdate>>>
    export type TipoVehiculoControllerUpdateMutationBody = UpdateTipoVehiculoDto
    export type TipoVehiculoControllerUpdateMutationError = AxiosError<void>

    /**
 * @summary Actualizar un tipo de vehículo
 */
export const useTipoVehiculoControllerUpdate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerUpdate>>, TError,{id: string;data: UpdateTipoVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tipoVehiculoControllerUpdate>>,
        TError,
        {id: string;data: UpdateTipoVehiculoDto},
        TContext
      > => {

      const mutationOptions = getTipoVehiculoControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Eliminar un tipo de vehículo por ID
 */
export const tipoVehiculoControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/tipo_vehiculo/${id}`,options
    );
  }



export const getTipoVehiculoControllerRemoveMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['tipoVehiculoControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tipoVehiculoControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  tipoVehiculoControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TipoVehiculoControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof tipoVehiculoControllerRemove>>>
    
    export type TipoVehiculoControllerRemoveMutationError = AxiosError<void>

    /**
 * @summary Eliminar un tipo de vehículo por ID
 */
export const useTipoVehiculoControllerRemove = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tipoVehiculoControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tipoVehiculoControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getTipoVehiculoControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Crear un vehículo
 */
export const vehiculoControllerCreate = (
    createVehiculoDto: CreateVehiculoDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehiculoDto>> => {
    
    
    return axios.post(
      `/vehiculo`,
      createVehiculoDto,options
    );
  }



export const getVehiculoControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerCreate>>, TError,{data: CreateVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerCreate>>, TError,{data: CreateVehiculoDto}, TContext> => {

const mutationKey = ['vehiculoControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vehiculoControllerCreate>>, {data: CreateVehiculoDto}> = (props) => {
          const {data} = props ?? {};

          return  vehiculoControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VehiculoControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof vehiculoControllerCreate>>>
    export type VehiculoControllerCreateMutationBody = CreateVehiculoDto
    export type VehiculoControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Crear un vehículo
 */
export const useVehiculoControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerCreate>>, TError,{data: CreateVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vehiculoControllerCreate>>,
        TError,
        {data: CreateVehiculoDto},
        TContext
      > => {

      const mutationOptions = getVehiculoControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Obtener todos los vehículos
 */
export const vehiculoControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehiculoDto[]>> => {
    
    
    return axios.get(
      `/vehiculo`,options
    );
  }


export const getVehiculoControllerFindAllQueryKey = () => {
    return [`/vehiculo`] as const;
    }

    
export const getVehiculoControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVehiculoControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof vehiculoControllerFindAll>>> = ({ signal }) => vehiculoControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VehiculoControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof vehiculoControllerFindAll>>>
export type VehiculoControllerFindAllQueryError = AxiosError<void>


export function useVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vehiculoControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof vehiculoControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vehiculoControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof vehiculoControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener todos los vehículos
 */

export function useVehiculoControllerFindAll<TData = Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVehiculoControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Obtener un vehículo por ID
 */
export const vehiculoControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehiculoDto>> => {
    
    
    return axios.get(
      `/vehiculo/${id}`,options
    );
  }


export const getVehiculoControllerFindOneQueryKey = (id: string,) => {
    return [`/vehiculo/${id}`] as const;
    }

    
export const getVehiculoControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError = AxiosError<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVehiculoControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof vehiculoControllerFindOne>>> = ({ signal }) => vehiculoControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VehiculoControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof vehiculoControllerFindOne>>>
export type VehiculoControllerFindOneQueryError = AxiosError<void>


export function useVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vehiculoControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof vehiculoControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vehiculoControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof vehiculoControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener un vehículo por ID
 */

export function useVehiculoControllerFindOne<TData = Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof vehiculoControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVehiculoControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Actualizar un vehículo
 */
export const vehiculoControllerUpdate = (
    id: string,
    updateVehiculoDto: UpdateVehiculoDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehiculoDto>> => {
    
    
    return axios.patch(
      `/vehiculo/${id}`,
      updateVehiculoDto,options
    );
  }



export const getVehiculoControllerUpdateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerUpdate>>, TError,{id: string;data: UpdateVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerUpdate>>, TError,{id: string;data: UpdateVehiculoDto}, TContext> => {

const mutationKey = ['vehiculoControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vehiculoControllerUpdate>>, {id: string;data: UpdateVehiculoDto}> = (props) => {
          const {id,data} = props ?? {};

          return  vehiculoControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VehiculoControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof vehiculoControllerUpdate>>>
    export type VehiculoControllerUpdateMutationBody = UpdateVehiculoDto
    export type VehiculoControllerUpdateMutationError = AxiosError<void>

    /**
 * @summary Actualizar un vehículo
 */
export const useVehiculoControllerUpdate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerUpdate>>, TError,{id: string;data: UpdateVehiculoDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vehiculoControllerUpdate>>,
        TError,
        {id: string;data: UpdateVehiculoDto},
        TContext
      > => {

      const mutationOptions = getVehiculoControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Eliminar un vehículo por ID
 */
export const vehiculoControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/vehiculo/${id}`,options
    );
  }



export const getVehiculoControllerRemoveMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['vehiculoControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof vehiculoControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  vehiculoControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VehiculoControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof vehiculoControllerRemove>>>
    
    export type VehiculoControllerRemoveMutationError = AxiosError<void>

    /**
 * @summary Eliminar un vehículo por ID
 */
export const useVehiculoControllerRemove = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof vehiculoControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof vehiculoControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getVehiculoControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Obtener todas las empresas
 */
export const empresaControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Empresa[]>> => {
    
    
    return axios.get(
      `/empresa`,options
    );
  }


export const getEmpresaControllerFindAllQueryKey = () => {
    return [`/empresa`] as const;
    }

    
export const getEmpresaControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof empresaControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEmpresaControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof empresaControllerFindAll>>> = ({ signal }) => empresaControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EmpresaControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof empresaControllerFindAll>>>
export type EmpresaControllerFindAllQueryError = AxiosError<void>


export function useEmpresaControllerFindAll<TData = Awaited<ReturnType<typeof empresaControllerFindAll>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof empresaControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof empresaControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmpresaControllerFindAll<TData = Awaited<ReturnType<typeof empresaControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof empresaControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof empresaControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmpresaControllerFindAll<TData = Awaited<ReturnType<typeof empresaControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener todas las empresas
 */

export function useEmpresaControllerFindAll<TData = Awaited<ReturnType<typeof empresaControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEmpresaControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Crear una empresa
 */
export const empresaControllerCreate = (
    createEmpresaDto: CreateEmpresaDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Empresa>> => {
    
    
    return axios.post(
      `/empresa`,
      createEmpresaDto,options
    );
  }



export const getEmpresaControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof empresaControllerCreate>>, TError,{data: CreateEmpresaDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof empresaControllerCreate>>, TError,{data: CreateEmpresaDto}, TContext> => {

const mutationKey = ['empresaControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof empresaControllerCreate>>, {data: CreateEmpresaDto}> = (props) => {
          const {data} = props ?? {};

          return  empresaControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EmpresaControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof empresaControllerCreate>>>
    export type EmpresaControllerCreateMutationBody = CreateEmpresaDto
    export type EmpresaControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Crear una empresa
 */
export const useEmpresaControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof empresaControllerCreate>>, TError,{data: CreateEmpresaDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof empresaControllerCreate>>,
        TError,
        {data: CreateEmpresaDto},
        TContext
      > => {

      const mutationOptions = getEmpresaControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Obtener una empresa por ID
 */
export const empresaControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Empresa>> => {
    
    
    return axios.get(
      `/empresa/${id}`,options
    );
  }


export const getEmpresaControllerFindOneQueryKey = (id: string,) => {
    return [`/empresa/${id}`] as const;
    }

    
export const getEmpresaControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof empresaControllerFindOne>>, TError = AxiosError<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEmpresaControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof empresaControllerFindOne>>> = ({ signal }) => empresaControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EmpresaControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof empresaControllerFindOne>>>
export type EmpresaControllerFindOneQueryError = AxiosError<void>


export function useEmpresaControllerFindOne<TData = Awaited<ReturnType<typeof empresaControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof empresaControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof empresaControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmpresaControllerFindOne<TData = Awaited<ReturnType<typeof empresaControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof empresaControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof empresaControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEmpresaControllerFindOne<TData = Awaited<ReturnType<typeof empresaControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener una empresa por ID
 */

export function useEmpresaControllerFindOne<TData = Awaited<ReturnType<typeof empresaControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof empresaControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEmpresaControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Actualizar una empresa
 */
export const empresaControllerUpdate = (
    id: string,
    updateEmpresaDto: UpdateEmpresaDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Empresa>> => {
    
    
    return axios.patch(
      `/empresa/${id}`,
      updateEmpresaDto,options
    );
  }



export const getEmpresaControllerUpdateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof empresaControllerUpdate>>, TError,{id: string;data: UpdateEmpresaDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof empresaControllerUpdate>>, TError,{id: string;data: UpdateEmpresaDto}, TContext> => {

const mutationKey = ['empresaControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof empresaControllerUpdate>>, {id: string;data: UpdateEmpresaDto}> = (props) => {
          const {id,data} = props ?? {};

          return  empresaControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EmpresaControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof empresaControllerUpdate>>>
    export type EmpresaControllerUpdateMutationBody = UpdateEmpresaDto
    export type EmpresaControllerUpdateMutationError = AxiosError<void>

    /**
 * @summary Actualizar una empresa
 */
export const useEmpresaControllerUpdate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof empresaControllerUpdate>>, TError,{id: string;data: UpdateEmpresaDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof empresaControllerUpdate>>,
        TError,
        {id: string;data: UpdateEmpresaDto},
        TContext
      > => {

      const mutationOptions = getEmpresaControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Eliminar una empresa por ID
 */
export const empresaControllerDelete = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/empresa/${id}`,options
    );
  }



export const getEmpresaControllerDeleteMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof empresaControllerDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof empresaControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['empresaControllerDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof empresaControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  empresaControllerDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EmpresaControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof empresaControllerDelete>>>
    
    export type EmpresaControllerDeleteMutationError = AxiosError<void>

    /**
 * @summary Eliminar una empresa por ID
 */
export const useEmpresaControllerDelete = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof empresaControllerDelete>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof empresaControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getEmpresaControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Crear un chofer
 */
export const choferControllerCreate = (
    createChoferDto: CreateChoferDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChoferDto>> => {
    
    
    return axios.post(
      `/chofer`,
      createChoferDto,options
    );
  }



export const getChoferControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof choferControllerCreate>>, TError,{data: CreateChoferDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof choferControllerCreate>>, TError,{data: CreateChoferDto}, TContext> => {

const mutationKey = ['choferControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof choferControllerCreate>>, {data: CreateChoferDto}> = (props) => {
          const {data} = props ?? {};

          return  choferControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChoferControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof choferControllerCreate>>>
    export type ChoferControllerCreateMutationBody = CreateChoferDto
    export type ChoferControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Crear un chofer
 */
export const useChoferControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof choferControllerCreate>>, TError,{data: CreateChoferDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof choferControllerCreate>>,
        TError,
        {data: CreateChoferDto},
        TContext
      > => {

      const mutationOptions = getChoferControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Obtener todos los choferes
 */
export const choferControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChoferDto[]>> => {
    
    
    return axios.get(
      `/chofer`,options
    );
  }


export const getChoferControllerFindAllQueryKey = () => {
    return [`/chofer`] as const;
    }

    
export const getChoferControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof choferControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChoferControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof choferControllerFindAll>>> = ({ signal }) => choferControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChoferControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof choferControllerFindAll>>>
export type ChoferControllerFindAllQueryError = AxiosError<void>


export function useChoferControllerFindAll<TData = Awaited<ReturnType<typeof choferControllerFindAll>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof choferControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof choferControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChoferControllerFindAll<TData = Awaited<ReturnType<typeof choferControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof choferControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof choferControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChoferControllerFindAll<TData = Awaited<ReturnType<typeof choferControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener todos los choferes
 */

export function useChoferControllerFindAll<TData = Awaited<ReturnType<typeof choferControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChoferControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Obtener un chofer por ID
 */
export const choferControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChoferDto>> => {
    
    
    return axios.get(
      `/chofer/${id}`,options
    );
  }


export const getChoferControllerFindOneQueryKey = (id: string,) => {
    return [`/chofer/${id}`] as const;
    }

    
export const getChoferControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof choferControllerFindOne>>, TError = AxiosError<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChoferControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof choferControllerFindOne>>> = ({ signal }) => choferControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChoferControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof choferControllerFindOne>>>
export type ChoferControllerFindOneQueryError = AxiosError<void>


export function useChoferControllerFindOne<TData = Awaited<ReturnType<typeof choferControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof choferControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof choferControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChoferControllerFindOne<TData = Awaited<ReturnType<typeof choferControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof choferControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof choferControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChoferControllerFindOne<TData = Awaited<ReturnType<typeof choferControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtener un chofer por ID
 */

export function useChoferControllerFindOne<TData = Awaited<ReturnType<typeof choferControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof choferControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChoferControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Actualizar un chofer
 */
export const choferControllerUpdate = (
    id: string,
    updateChoferDto: UpdateChoferDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ChoferDto>> => {
    
    
    return axios.patch(
      `/chofer/${id}`,
      updateChoferDto,options
    );
  }



export const getChoferControllerUpdateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof choferControllerUpdate>>, TError,{id: string;data: UpdateChoferDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof choferControllerUpdate>>, TError,{id: string;data: UpdateChoferDto}, TContext> => {

const mutationKey = ['choferControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof choferControllerUpdate>>, {id: string;data: UpdateChoferDto}> = (props) => {
          const {id,data} = props ?? {};

          return  choferControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChoferControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof choferControllerUpdate>>>
    export type ChoferControllerUpdateMutationBody = UpdateChoferDto
    export type ChoferControllerUpdateMutationError = AxiosError<void>

    /**
 * @summary Actualizar un chofer
 */
export const useChoferControllerUpdate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof choferControllerUpdate>>, TError,{id: string;data: UpdateChoferDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof choferControllerUpdate>>,
        TError,
        {id: string;data: UpdateChoferDto},
        TContext
      > => {

      const mutationOptions = getChoferControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Eliminar un chofer por ID
 */
export const choferControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/chofer/${id}`,options
    );
  }



export const getChoferControllerRemoveMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof choferControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof choferControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['choferControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof choferControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  choferControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChoferControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof choferControllerRemove>>>
    
    export type ChoferControllerRemoveMutationError = AxiosError<void>

    /**
 * @summary Eliminar un chofer por ID
 */
export const useChoferControllerRemove = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof choferControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof choferControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getChoferControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
